apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      initContainers:
        - name: take-data-dir-ownership
          image: alpine:3
          command:
            - chown
            - -R
            - 1000:1000
            - /prometheus
          volumeMounts:
            - name: data
              mountPath: /prometheus
      containers:
        - image: prom/prometheus:latest
          name: prometheus
          command:
            [
              "/bin/prometheus",
              "--config.file=/etc/config/prometheus/config.yaml",
              "--web.enable-remote-write-receiver",
              "--enable-feature=exemplar-storage",
            ]
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config
              mountPath: /etc/config/prometheus
            - name: data
              mountPath: /prometheus
      volumes:
        - name: config
          configMap:
            name: prometheus-config
        - name: data
          persistentVolumeClaim:
            claimName: prometheus-data
---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: prometheus
  labels:
    svc: prometheus
spec:
  type: ClusterIP # Only access from within the Cluster
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      name: prometheus
  selector:
    app: prometheus
