apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  config.yaml: |
    scrape_configs:
      - job_name: 'collector'
        scrape_interval: 15s
        static_configs:
          - targets: ['otel-collector:9464']
