apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-state-metrics
  name: kube-state-metrics
  namespace: monitoring
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
    - name: self-metrics
      port: 8081
      targetPort: self-metrics
  selector:
    app: kube-state-metrics
